swipe:
        4:
                left:
                        workspace: 'next'
                right:
                        workspace: 'prev'
        3:
                right:
                        command: "xdotool key alt+Right"
                left:
                        command: "xdotool key alt+Left"
                down:
                        window:
                                fullscreen: toggle

                        #pinch:
                        #  in:
                        #    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
                        #  out:
                        #    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
                        #
threshold:
        pinch: 0.3

interval:
        pinch: 0.4
        swipe: 0.75

